; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = 
	../screenLIB/lib
extra_scripts = 
	pre:pre_build_screen_script.py
	pre:pre_build_version_script.py
	post:post_build_script.py
	post:post_build_ui_script.py
board_build.cxx_std = 17
board_build.filesytem = littlefs
board_build.fs_dir = data
board_build.partitions = default_4MB.csv
build_flags = 
	-I src
	-I ../ScreenUI
	-I ../ScreenUI/generated/shared
build_src_filter = 
	+<*>
	-<backend_main.cpp>
lib_deps = 
	adafruit/Adafruit MCP23017 Arduino Library@^2.3.2
	bblanchon/ArduinoJson @ ^7.0.4
	knolleary/PubSubClient@^2.8
	links2004/WebSockets@^2.6.1
	nanopb/Nanopb @ ^0.4.9

[env:screenprep_native]
platform = native
lib_extra_dirs =
	../screenLIB/lib
extra_scripts =
	pre:pre_build_screen_script.py
lib_compat_mode = off
build_flags =
	-I src
	-I ../ScreenUI
	-I ../ScreenUI/generated/shared
build_src_filter =
	+<backend_main.cpp>
	+<Screen/>
lib_deps =
	bblanchon/ArduinoJson @ ^7.0.4
	nanopb/Nanopb @ ^0.4.9
